VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "PBEasyFinBankAccountForm"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public BankCode As String
Public AccountNumber As String
Public AccountPWD As String
Public AccountType As String
Public IdentityNumber As String
Public AccountName As String
Public BankID As String
Public FastID As String
Public FastPWD As String
Public UsePeriod As String
Public Memo As String



